### ISSUE TITLE
DEFINE-TEST-PACKAGE should export RUN-PACKAGE-TESTS

### ISSUE THREAD

**Issue by PuercoPop** [joaotavora/fiasco#16]
As it is one of the entry point to call the tests or it meant only for interactive testing? I am there are other entry points such us being fiasco:run-suite-tests

**Comment by joaotavora** [comment]
Hi, sorry for being almost one year late in replying to this. Haven't we been down this road once. I recall having made this mistake earlier, whereby using `package-a:run-package-tests` from `package-b` *doesn't* do the expected thing and ends up running `package-b`'s tests instead. I believe this is supplanted by #17, which lets you `(fiasco:run-tests :package-b)`?

**Comment by PuercoPop** [comment]
Indeed
