### ISSUE TITLE
infinite recursion in recent synonym-stream introduction

### ISSUE THREAD

**Issue by tarballs-are-good** [joaotavora/fiasco#19]
Commit fe89c0e924c22c667cc11c6fc6e79419fc7c1a8b introduced unstable behavior in SBCL (and probably all Lisp implementations). Running (some?) tests cause infinite recursion.

The reduced test case is:

```
CL-USER> (let ((*standard-output* fiasco:*test-run-standard-output*))
           (format t "x"))
Control stack guard page temporarily disabled: proceed with caution
```

which more or less appears in the `deftest` macro. This is equivalent to

```
CL-USER> (let ((*standard-output* (make-synonym-stream '*standard-output*)))
           (format t "x"))
```

I think the infinite recursion makes sense because the symbol is looked up dynamically.

**Comment by tarballs-are-good** [comment]
CC @PuercoPop @joaotavora

**Comment by joaotavora** [comment]
Reverted it, mostly since it was a "nice to have". Follow discussion on #14.

**Comment by joaotavora** [comment]
> Follow discussion on #14.

Nah, let's continue here. Apparently a pull request can't be reopened.

So @tarballs-are-good, while I don't mind reverting this at all:

* I don't understand is how fiasco's self tests didn't catch this.
* I wonder if this is actually SBCL's fault. Shouldn't it be a noop? `(let ((*standard-output* *standard-output*)) ...)`

**Comment by joaotavora** [comment]
So here's me answering my own questions.

> I wonder if this is actually SBCL's fault. Shouldn't it be a noop? 

ECL locks up too, all other probably, too.

> I don't understand is how fiasco's self tests didn't catch this.

Because they don't print anything to `stdout`.

```
CL-USER> (deftest bla () (format t "x"))
CL-USER> (bla)
```
is enough to trigger the error.

**Comment by tarballs-are-good** [comment]
The reason is that we bind `*standard-output*` to an object `X` such that when `X` is written to, it's value is determined. The value is whatever `(eval '*standard-output*)` is equivalently, which is of course `X`, leading to infinite recursion.

**Comment by tarballs-are-good** [comment]
I might suggest that the global variable is just bound to `(load-time-value *standard-output*)`. You get rid of eval, and you can bind the variable to whatever stream you want at runtime.

**Comment by joaotavora** [comment]
> such that when X is written to, it's value is determined. 

Thanks, I'd gotten that far though.

> I might suggest that the global variable is just bound to (load-time-value *standard-output*). You get rid of eval, and you can bind the variable to whatever stream you want at runtime.

Personally, I'd rather get rid of `fiasco:*test-run-standard-output*` completely. It was inherited from stefil (but even @attila-lendvai doesn't recall it).  I don't understand why it's needed and I've never seen this idiom before. . To redirect to file, for example I'd just `(with-open-file (*standard-output* "something" :direction :output) (run-some-test))`

**Comment by PuercoPop** [comment]
@tarballs-are-good May I ask why would you want to bind `*standard-output*` to `*test-run-standard-output*`instead of the other way around? That is the way synonym streams are meant to be used.*

But either way fe89c0e924c22c667cc11c6fc6e79419fc7c1a8b is buggy. The problem was that it was a half measure. My impression is that Stefil's mechanism of binding a  was to avoid the same issue synonym streams solve: That the value of the symbol tracks the value of *standard-output* instead of keep that value `*standard-output*` had when the file was loaded. @attila-lendvai am I under the right impression?

I've submitted a '3/4' measure addressing the bug in https://github.com/joaotavora/fiasco/pull/20

**Comment by tarballs-are-good** [comment]
I have no particular preference on what gets bound to what. I just print to standard out, which hasn’t been otherwise problematic for me.

**Comment by attila-lendvai** [comment]
i have never been familiar with `synonym-stream`, so it may very well be the case.
