### ISSUE TITLE
Provide mechanism to skip a test

### ISSUE THREAD

**Issue by stylewarning** [joaotavora/fiasco#25]
It would be good if Fiasco had a way that the test opted to skip itself. Example:

```
(fiasco:deftest test-socket ()
  (when os-is-windows
    (fiasco:skip-test))
  ...)
```

Prefer not to use `#-windows` as I think that's bad practice.

**Comment by joaotavora** [comment]
This would be welcome indeed, though I would name it just `fiasco:skip`, to bring it slightly closer to the Emacs Regression Tests library (ert).
