### ISSUE TITLE
Are the TravisCI test run exit codes correct?

### ISSUE THREAD

**Issue by enzuru** [joaotavora/fiasco#33]
So maybe I don't understand the test suite, but it seems like the tests are failing despite being green: https://travis-ci.org/github/joaotavora/fiasco

But since the exit code is `0` TravisCI doesn't know any better.

**Comment by enzuru** [comment]
Also, unrelated but potentially helpful, it seems like your website is down: http://joaotavora.com/

**Comment by joaotavora** [comment]
What is failing about the tests?
```
(fiasco:run-tests 
                       (quote (:fiasco-basic-self-tests
                               :fiasco-intro-example
                               :fiasco-suite-tests
                               )))
FIASCO-BASIC-SELF-TESTS (Suite)
  LIFECYCLE
WARNING: redefining #:TEMP-TEST601 in DEFUN
WARNING: redefining #:TRANSIENT-TEST602 in DEFUN
..........................................................................[ OK ]
  COUNTER-IN-LEXICAL-ENVIRONMENT..........................................[ OK ]
  ASSERTIONS..............................................................[ OK ]
  SLIGHTLY-VERBOSE-TEST
Watch out for me..........................................................[ OK ]
  SLIGHTLY-VERBOSE-TEST-2...And me........................................[ OK ]
  LAMBDA-LIST-PROCESSING..................................................[ OK ]

FIASCO-INTRO-EXAMPLE (Suite)
  INTRO-METATEST

Test run had 3 failures:

  Failure 1: UNEXPECTED-ERROR when running FIASCO-EXAMPLES::DOUBLE-CONVERSION
    The variable FIASCO-EXAMPLE-TIME::G0 is unbound.

  Failure 2: UNEXPECTED-ERROR when running FIASCO-EXAMPLES::TEST-CONVERSION-TO-SECONDS
    The variable FIASCO-EXAMPLE-TIME::G0 is unbound.

  Failure 3: FAILED-ASSERTION when running FIASCO-EXAMPLES::TEST-CONVERSION-TO-HOURS-AND-MINUTES
    Binary predicate (EQUAL X Y) failed.
    x: (FIASCO-EXAMPLE-TIME:HOURS-AND-MINUTES 4500) => (1 75)
    y: '(1 15) => (1 15)
..........................................................................[ OK ]

FIASCO-SUITE-TESTS (Suite)
  TEST-NESTED-SUITES......................................................[ OK ]
  TEST-TOP-SUITES
WARNING: redefining #:TEMP-TEST615 in DEFUN
WARNING: redefining #:TRANSIENT-TEST616 in DEFUN
Watch out for me...And me

Test run had 3 failures:

  Failure 1: UNEXPECTED-ERROR when running FIASCO-EXAMPLES::DOUBLE-CONVERSION
    The variable FIASCO-EXAMPLE-TIME::G0 is unbound.

  Failure 2: UNEXPECTED-ERROR when running FIASCO-EXAMPLES::TEST-CONVERSION-TO-SECONDS
    The variable FIASCO-EXAMPLE-TIME::G0 is unbound.

  Failure 3: FAILED-ASSERTION when running FIASCO-EXAMPLES::TEST-CONVERSION-TO-HOURS-AND-MINUTES
    Binary predicate (EQUAL X Y) failed.
    x: (FIASCO-EXAMPLE-TIME:HOURS-AND-MINUTES 4500) => (1 75)
    y: '(1 15) => (1 15)


Test run had 3 failures:

  Failure 1: UNEXPECTED-ERROR when running FIASCO-EXAMPLES::DOUBLE-CONVERSION
    The variable FIASCO-EXAMPLE-TIME::G0 is unbound.

  Failure 2: UNEXPECTED-ERROR when running FIASCO-EXAMPLES::TEST-CONVERSION-TO-SECONDS
    The variable FIASCO-EXAMPLE-TIME::G0 is unbound.

  Failure 3: FAILED-ASSERTION when running FIASCO-EXAMPLES::TEST-CONVERSION-TO-HOURS-AND-MINUTES
    Binary predicate (EQUAL X Y) failed.
    x: (FIASCO-EXAMPLE-TIME:HOURS-AND-MINUTES 4500) => (1 75)
    y: '(1 15) => (1 15)
..........................................................................[ OK ]

T
(#<test-run of FIASCO-BASIC-SELF-TESTS: 7 tests, 40 assertions, 0 failures in 0.088 sec>
 #<test-run of FIASCO-INTRO-EXAMPLE: 2 tests, 9 assertions, 0 failures in 0.001 sec>
 #<test-run of FIASCO-SUITE-TESTS: 8 tests, 6 assertions, 0 failures in 0.124 sec>)
FIASCO-BASIC-SELF-TESTS> 
```

bq. Also, unrelated but potentially helpful, it seems like your website is down:

Thanks. It did help.  I switched a piece of technology recently and it break often, for some weird reason.

**Comment by enzuru** [comment]
```
Test run had 3 failures:

  Failure 1: UNEXPECTED-ERROR when running FIASCO-EXAMPLES::DOUBLE-CONVERSION
    The variable FIASCO-EXAMPLE-TIME::G0 is unbound.
```

Most test suites throw errors like this on failure (wouldn't a success at best be an *expected* error)? I guess I just don't understand the test suite quite yet! I still plan on using the test suite for my project, but the logs on your CI build just threw me off. Sorry for the interruption.

**Comment by joaotavora** [comment]
@enzuru 

What you are looking at is Fiasco's own test suite, right?  What is Fiasco?  It is a test framework.  So when testing _itself_, it must test the situation where it is testing something that eventually fails. So what you see there is a _metatest_, a test about a test.  The latter is  supposed to fail so that the former can verify that failures are correctly reported.  The failure you see about is from the intra-test, a test designed to fail, so that the metatest can pick up on that failure. So everything is OK.

If this is hard to grasp, don't worry. Presumably you won't be testing Fiasco itself, you will be testing some other application, say, a beer brewing application, _using Fiasco_.  Have a look at Snooze's test suite ([here](https://github.com/joaotavora/snooze/blob/master/snooze-tests.lisp) and [here](https://travis-ci.org/github/joaotavora/snooze/jobs/715093268)), for example.  That showcases the normal use of Fiasco, its ability to test other programs.

**Comment by joaotavora** [comment]
> Most test suites throw errors like this on failure (wouldn't a success at best be an expected error)? 

Also, this isn't an error thrown, technically, it is just a printout.  Fiasco's tests do signal Lisp conditions, that you can handle. But I'll leave that explanation for later, if you think it's worth it.

**Comment by enzuru** [comment]
That makes perfect sense, thank you @joaotavora for your patient explanation.
